#
# Definitions for nvcc code build for PG-Strom
#

# standalone build?
ifeq ($(STROM_BUILD_ROOT),)
PG_CONFIG       ?= pg_config
endif

# PostgreSQL storage constants required by code that cannot include
# postgres.h.  Keep standalone device builds synchronized as well as builds
# driven by the extension Makefile.
PG_INCLUDEDIR_SERVER := $(shell $(PG_CONFIG) --includedir-server)
PG_CONFIG_HEADER := $(PG_INCLUDEDIR_SERVER)/pg_config.h
PG_CONFIG_MANUAL_HEADER := $(PG_INCLUDEDIR_SERVER)/pg_config_manual.h
PG_BUFPAGE_HEADER := $(PG_INCLUDEDIR_SERVER)/storage/bufpage.h

PGSTROM_DEVICE_NAMEDATALEN := $(shell awk 'substr($$1, 2) == "define" && $$2 == "NAMEDATALEN" {print $$3; exit}' $(PG_CONFIG_MANUAL_HEADER) 2>/dev/null)
PGSTROM_DEVICE_BLCKSZ := $(shell awk 'substr($$1, 2) == "define" && $$2 == "BLCKSZ" {print $$3; exit}' $(PG_CONFIG_HEADER) 2>/dev/null)
PGSTROM_DEVICE_RELSEG_SIZE := $(shell awk 'substr($$1, 2) == "define" && $$2 == "RELSEG_SIZE" {print $$3; exit}' $(PG_CONFIG_HEADER) 2>/dev/null)
PGSTROM_DEVICE_PAGE_LAYOUT_VERSION := $(shell awk 'substr($$1, 2) == "define" && $$2 == "PG_PAGE_LAYOUT_VERSION" {print $$3; exit}' $(PG_BUFPAGE_HEADER) 2>/dev/null)
PGSTROM_DEVICE_MAXIMUM_ALIGNOF := $(shell awk 'substr($$1, 2) == "define" && $$2 == "MAXIMUM_ALIGNOF" {print $$3; exit}' $(PG_CONFIG_HEADER) 2>/dev/null)

ifeq ($(strip $(PGSTROM_DEVICE_NAMEDATALEN)),)
$(error unable to read NAMEDATALEN from $(PG_CONFIG_MANUAL_HEADER))
endif
ifeq ($(strip $(PGSTROM_DEVICE_BLCKSZ)),)
$(error unable to read BLCKSZ from $(PG_CONFIG_HEADER))
endif
ifeq ($(strip $(PGSTROM_DEVICE_RELSEG_SIZE)),)
$(error unable to read RELSEG_SIZE from $(PG_CONFIG_HEADER))
endif
ifeq ($(strip $(PGSTROM_DEVICE_PAGE_LAYOUT_VERSION)),)
$(error unable to read PG_PAGE_LAYOUT_VERSION from $(PG_BUFPAGE_HEADER))
endif
ifeq ($(strip $(PGSTROM_DEVICE_MAXIMUM_ALIGNOF)),)
$(error unable to read MAXIMUM_ALIGNOF from $(PG_CONFIG_HEADER))
endif

#
# Header and Libraries of CUDA
#
CUDA_PATH_LIST := /usr/local/cuda /usr/local/cuda-*
CUDA_PATH := $(shell for x in $(CUDA_PATH_LIST);    \
           do test -e "$$x/include/cuda.h" && echo $$x; done | head -1)
CUDA_IPATH := $(CUDA_PATH)/include
CUDA_BPATH := $(CUDA_PATH)/bin
CUDA_LPATH := $(CUDA_PATH)/lib64
NVCC       := $(CUDA_BPATH)/nvcc
NVCC_VERSION := $(shell $(NVCC) --version | grep ^Cuda | \
                  grep -o -E 'V[0-9\.]+$$' |             \
		  sed -e 's/V//g' -e 's/\./ /g' |        \
		  awk '{ printf("%06u", $$1 * 1000 + $$2 * 10); }')
# Max number of registers per GPU thread for PG-Strom modules
# (64k / 128 = up to 512 threads per SM)
MAXREGCOUNT := 128
MAXTHREADS_PER_BLOCK := $(shell expr 65536 / $(MAXREGCOUNT))

__NUM_GPUS := $(shell ls -d /proc/driver/nvidia/gpus/*/information | wc -l)
ifeq ($(__NUM_GPUS),0)
__NVCC_TARGET := --gpu-architecture=compute_60 \
                 --gpu-code=sm_60,sm_61,sm_70,sm_75,sm_80,sm_86,sm_89,sm_90 \
                 --threads 8
else
__NVCC_TARGET := --gpu-architecture=native
endif

# flags to build GPU libraries
__NVCC_CFLAGS += -I $(PG_INCLUDEDIR_SERVER)             \
                 --maxrregcount=$(MAXREGCOUNT)           \
                 --source-in-ptx -lineinfo               \
                 -DHAVE_FLOAT2                           \
                 -DCUDA_MAXTHREADS_PER_BLOCK=$(MAXTHREADS_PER_BLOCK) \
                 $(__NVCC_TARGET)
__NVCC_LDFLAGS += -Xnvlink --suppress-stack-size-warning \
                  $(__NVCC_TARGET)
# nvcc flags
NVCC_CFLAGS  = $(__NVCC_CFLAGS)  $(NVCC_FLAGS_CUSTOM) $(NVCC_CFLAGS_CUSTOM)
NVCC_LDFLAGS = $(__NVCC_LDFLAGS) $(NVCC_FLAGS_CUSTOM) $(NVCC_LDFLAGS_CUSTOM)

# PG-Strom GPU Code
__CUDA_CORE_FILES = xpu_common cuda_gpuscan cuda_gpujoin cuda_gpupreagg cuda_gpusort \
                    xpu_basetype xpu_numeric xpu_timelib xpu_textlib \
                    xpu_misclib  xpu_jsonlib xpu_postgis
__CUDA_CORE_HEADERS = pgstrom_device_config.h \
                      cuda_common.h xpu_common.h xpu_opcodes.h xpu_basetype.h \
                      xpu_numeric.h xpu_textlib.h xpu_timelib.h xpu_misclib.h \
                      xpu_jsonlib.h xpu_postgis.h
CUDA_OBJS = $(addsuffix .o, $(__CUDA_CORE_FILES) $(CUDA_CUSTOM_FILES))
CUDA_SRCS = $(addsuffix .cu,$(__CUDA_CORE_FILES) $(CUDA_CUSTOM_FILES))
CUDA_HEADERS = $(__CUDA_CORE_HEADERS) $(CUDA_CUSTOM_HEADERS)
CUDA_HASH_HEADERS = $(filter-out pgstrom_device_config.h,$(CUDA_HEADERS))
CUDA_BUILD_CONFIG = NAMEDATALEN=$(PGSTROM_DEVICE_NAMEDATALEN),BLCKSZ=$(PGSTROM_DEVICE_BLCKSZ),RELSEG_SIZE=$(PGSTROM_DEVICE_RELSEG_SIZE),PG_PAGE_LAYOUT_VERSION=$(PGSTROM_DEVICE_PAGE_LAYOUT_VERSION),MAXIMUM_ALIGNOF=$(PGSTROM_DEVICE_MAXIMUM_ALIGNOF)
CUDA_MD5SUM = $(shell (printf '%s' '$(CUDA_BUILD_CONFIG)'; cat $(CUDA_HASH_HEADERS) $(CUDA_SRCS)) | md5sum | awk '{print $$1}')
CUDA_FATBIN = pgstrom-gpucode-V$(NVCC_VERSION)-$(CUDA_MD5SUM).fatbin
