PG_CONFIG ?= pg_config
VERSION ?= 6.1
RELEASE ?= 0
GITHASH_IF_NOT_GIVEN := 4d12ef415759dc48cd4c1421565e9c694b7bd3f9
# This vendored tree has no nested .git directory.  Do not accidentally stamp
# the surrounding Cloudberry repository commit into the PG-Strom binary.
GITHASH := $(GITHASH_IF_NOT_GIVEN)
PGSTROM_GITHASH := $(GITHASH_IF_NOT_GIVEN)::cloudberry_mvp

#
# PostgreSQL major version
#
PG_MAJORVERSION := $(shell $(PG_CONFIG) --version | sed 's/\./ /g' | awk '{print $$2}')
PG_MINORVERSION := $(shell $(PG_CONFIG) --version | sed 's/\./ /g' | awk '{print $$3}')

#
# PG-Strom version signature
#
ifeq ($(shell echo $(RELEASE) | grep -E '^[0-9]+'),)
PGSTROM_VERSION := $(VERSION)$(RELEASE)
else
PGSTROM_VERSION := $(VERSION).$(RELEASE)
endif

#
# GitHash to build
#
ifeq ($(GITHASH),)
GITHASH := $(shell git rev-parse HEAD 2>/dev/null)
ifeq ($(GITHASH),)
GITHASH := $(GITHASH_IF_NOT_GIVEN)
else
ifeq ($(shell git diff | wc -l),0)
PGSTROM_GITHASH := $(GITHASH)
else
PGSTROM_GITHASH := $(GITHASH)::local_changes
endif
endif
endif
