#!/usr/bin/env bash
set -euo pipefail

demo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export PGSTROM_MVP_TEST_OPERATOR=gpupreagg
export PGSTROM_MVP_TARGET_CONTENT="${PGSTROM_GPUPREAGG_TARGET_CONTENT:-${PGSTROM_MVP_TARGET_CONTENT:-0}}"
export PGSTROM_MVP_RECOVERY_CYCLES="${PGSTROM_GPUPREAGG_RECOVERY_CYCLES:-${PGSTROM_MVP_RECOVERY_CYCLES:-3}}"
export PGSTROM_MVP_RECOVERY_TIMEOUT="${PGSTROM_GPUPREAGG_RECOVERY_TIMEOUT:-${PGSTROM_MVP_RECOVERY_TIMEOUT:-30}}"
export PGSTROM_MVP_ALLOW_SERVICE_RESTART="${PGSTROM_GPUPREAGG_ALLOW_SERVICE_RESTART:-${PGSTROM_MVP_ALLOW_SERVICE_RESTART:-0}}"
export PGSTROM_MVP_ALLOW_HARD_FAILURE="${PGSTROM_GPUPREAGG_ALLOW_HARD_FAILURE:-${PGSTROM_MVP_ALLOW_HARD_FAILURE:-0}}"
export PGSTROM_MVP_SERVICE_SIGNAL="${PGSTROM_GPUPREAGG_SERVICE_SIGNAL:-${PGSTROM_MVP_SERVICE_SIGNAL:-HUP}}"

exec "$demo_dir/run_failure_recovery.sh"
