#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)
gpu_scan="$repo_root/gpcontrib/pg_strom/src/gpu_scan.c"
gpu_preagg="$repo_root/gpcontrib/pg_strom/src/gpu_preagg.c"
gpu_cache="$repo_root/gpcontrib/pg_strom/src/gpu_cache.c"
cdbplan="$repo_root/src/backend/cdb/cdbplan.c"
makefile="$repo_root/gpcontrib/pg_strom/src/Makefile"
main_c="$repo_root/gpcontrib/pg_strom/src/main.c"
gpu_service="$repo_root/gpcontrib/pg_strom/src/gpu_service.c"
demo_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_demo.sh"
failure_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_failure_recovery.sh"
cancel_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_query_cancel.sh"
gpupreagg_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_gpupreagg_mvp.sh"
gpupreagg_m4b_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_gpupreagg_m4b.sh"
gpupreagg_m5a_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_gpupreagg_m5a.sh"
gpupreagg_having_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_gpupreagg_having.sh"
gpupreagg_cancel_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_gpupreagg_cancel.sh"
gpupreagg_failure_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_gpupreagg_failure_recovery.sh"
budget_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_shared_gpu_budget.sh"
budget_matrix_runner="$repo_root/gpcontrib/pg_strom/cloudberry/demo/run_shared_gpu_concurrency_matrix.sh"
upgrade_sql="$repo_root/gpcontrib/pg_strom/src/sql/pg_strom--6.0--6.1.sql"
budget_upgrade_sql="$repo_root/gpcontrib/pg_strom/src/sql/pg_strom--6.1--6.2.sql"
budget_static_upgrade_sql="$repo_root/gpcontrib/pg_strom/src/sql/pg_strom--6.2--6.3.sql"
demo_config="$repo_root/gpcontrib/pg_strom/cloudberry/demo/postgresql.conf.mvp"
demo_setup="$repo_root/gpcontrib/pg_strom/cloudberry/demo/setup.sql"
demo_verify="$repo_root/gpcontrib/pg_strom/cloudberry/demo/verify.sql"
demo_readme="$repo_root/gpcontrib/pg_strom/cloudberry/demo/README.md"
host_quals_design="$repo_root/gpcontrib/pg_strom/CLOUDBERRY_GPUSCAN_HOST_QUALS_DESIGN.md"
host_quals_milestone="$repo_root/gpcontrib/pg_strom/CLOUDBERRY_GPUSCAN_HOST_QUALS_MILESTONE.md"
gpupreagg_design="$repo_root/gpcontrib/pg_strom/CLOUDBERRY_GPUPREAGG_MVP_DESIGN.md"
gpupreagg_m4b_design="$repo_root/gpcontrib/pg_strom/CLOUDBERRY_GPUPREAGG_M4B_DESIGN.md"
gpupreagg_m5a_design="$repo_root/gpcontrib/pg_strom/CLOUDBERRY_GPUPREAGG_M5A_DESIGN.md"
gpupreagg_having_design="$repo_root/gpcontrib/pg_strom/CLOUDBERRY_GPUPREAGG_HAVING_DESIGN.md"
budget_design="$repo_root/gpcontrib/pg_strom/CLOUDBERRY_SHARED_GPU_BUDGET_DESIGN.md"

require_text() {
    local pattern=$1
    local file=$2
    if ! grep -Eq "$pattern" "$file"; then
        echo "missing expected MVP guard: $pattern in $file" >&2
        exit 1
    fi
}

require_text 'cdbpathlocus_from_baserel' "$gpu_scan"
require_text 'const CustomScan \*cscan = \(const CustomScan \*\)plan' "$gpu_scan"
require_text 'planner_segment_count\(baserel->cdbpolicy\)' "$gpu_scan"
require_text 'disk_cost = .*baserel->pages / segment_divisor' "$gpu_scan"
require_text 'path\.rescannable = true' "$gpu_scan"
require_text 'path\.sameslice_relids = baserel->relids' "$gpu_scan"
require_text 'GpPolicyIsPartitioned\(baserel->cdbpolicy\)' "$gpu_scan"
require_text 'if \(optimizer\)' "$gpu_scan"
require_text 'baserel->reloptkind == RELOPT_OTHER_MEMBER_REL' "$gpu_scan"
require_text '!allow_host_quals && pp_info->host_quals != NIL' "$gpu_scan"
require_text 'pg_strom\.cloudberry_enable_host_quals' "$gpu_scan"
require_text 'cloudberry_enable_host_quals = false' "$gpu_scan"
require_text '&cloudberry_enable_host_quals' "$gpu_scan"
require_text 'cloudberry_enable_host_quals,' "$gpu_scan"
require_text 'At least one GPU executable qualifier is still required' "$gpu_scan"
require_text 'MUTATE\(newcscan->custom_plans' "$cdbplan"
require_text 'MUTATE\(newcscan->custom_exprs' "$cdbplan"
require_text 'MUTATE\(newcscan->custom_scan_tlist' "$cdbplan"
if grep -A18 'case T_CustomScan:' "$cdbplan" | grep -q 'MUTATE.*custom_private'; then
    echo 'custom_private must remain opaque to the CustomScan mutator' >&2
    exit 1
fi
require_text 'PGSTROM_WITH_ARROW.*\?= 1' "$makefile"
require_text 'GENERATED-HEADERS.*pgstrom_device_config\.h' "$makefile"
require_text 'PGSTROM_DEVICE_BLCKSZ.*BLCKSZ' "$repo_root/gpcontrib/pg_strom/src/Makefile.cuda"
require_text 'PGSTROM_DEVICE_RELSEG_SIZE.*RELSEG_SIZE' "$repo_root/gpcontrib/pg_strom/src/Makefile.cuda"
require_text 'PGSTROM_DEVICE_PAGE_LAYOUT_VERSION.*PG_PAGE_LAYOUT_VERSION' "$repo_root/gpcontrib/pg_strom/src/Makefile.cuda"
require_text '__CUDA_CORE_HEADERS = pgstrom_device_config\.h' "$repo_root/gpcontrib/pg_strom/src/Makefile.cuda"
require_text 'CUDA_BUILD_CONFIG = NAMEDATALEN=.*BLCKSZ=.*RELSEG_SIZE=.*PG_PAGE_LAYOUT_VERSION=.*MAXIMUM_ALIGNOF=' "$repo_root/gpcontrib/pg_strom/src/Makefile.cuda"
require_text '#include "pgstrom_device_config\.h"' "$repo_root/gpcontrib/pg_strom/src/xpu_common.h"
require_text '#define BLCKSZ.*PGSTROM_DEVICE_BLCKSZ' "$repo_root/gpcontrib/pg_strom/src/xpu_common.h"
require_text 'Must match CUDA_BUILD_CONFIG in Makefile\.cuda exactly' "$gpu_service"
if grep -Eq '^#define BLCKSZ[[:space:]]+8192' \
    "$repo_root/gpcontrib/pg_strom/src/xpu_common.h"; then
    echo 'device BLCKSZ must come from the target server configuration' >&2
    exit 1
fi
require_text '#ifndef GP_VERSION_NUM' "$main_c"
require_text 'pgstrom_init_gpu_preagg\(\);' "$main_c"
require_text 'path\.memory.*= subpath->memory' "$main_c"
require_text 'path\.locus.*= subpath->locus' "$main_c"
require_text 'cloudberry_gpupreagg_query_supported' "$gpu_preagg"
require_text 'Cloudberry GpuPreAgg MVP does not support aggregate' "$gpu_preagg"
require_text 'upper_stage != UPPERREL_GROUP_AGG' "$gpu_preagg"
require_text 'parse->distinctClause != NIL' "$gpu_preagg"
require_text 'expression_tree_walker\(\(Node \*\)parse->havingQual' "$gpu_preagg"
require_text 'Cloudberry always executes a CPU final aggregate after GpuPreAgg' "$gpu_preagg"
require_text 'Cloudberry GpuPreAgg HAVING passed query eligibility' "$gpu_preagg"
require_text 'Cloudberry GpuPreAgg HAVING target rewrite rejected' "$gpu_preagg"
require_text 'Cloudberry GpuPreAgg HAVING path constructed' "$gpu_preagg"
require_text 'Cloudberry GpuPreAgg HAVING final path' "$gpu_preagg"
require_text 'extra->patype != PARTITIONWISE_AGGREGATE_NONE' "$gpu_preagg"
require_text 'GpPolicyIsPartitioned\(input_rel->cdbpolicy\)' "$gpu_preagg"
require_text 'op_leaf->pp_info->scan_quals == NIL' "$gpu_preagg"
require_text 'op_leaf->pp_info->host_quals != NIL' "$gpu_preagg"
require_text 'needs_cpu_final = true' "$gpu_preagg"
require_text 'CdbPathLocus_MakeStrewn\(&output_locus' "$gpu_preagg"
require_text 'CdbPathLocus_MakeSingleQE\(&singleqe_locus' "$gpu_preagg"
require_text 'cdbpath_create_motion_path\(con->root' "$gpu_preagg"
require_text 'groupby_collocated' "$gpu_preagg"
require_text 'cdbpathlocus_pull_above_projection\(con->root' "$gpu_preagg"
require_text 'parse->groupClause != NIL && con->groupby_collocated' "$gpu_preagg"
require_text '!con->groupby_collocated &&' "$gpu_preagg"
require_text 'num_groups = con->num_groups' "$gpu_preagg"
require_text 'cpath->path.locus.*= output_locus' "$gpu_preagg"
require_text 'estimate_num_groups_on_segment\(final_num_groups' "$gpu_preagg"
require_text 'cdbpathlocus_collocates_tlist\(root, input_locus, group_tles\)' "$gpu_preagg"
require_text '&group_tles,[[:space:]]*$' "$gpu_preagg"
require_text '&group_sortops,[[:space:]]*$' "$gpu_preagg"
require_text '&group_eqops\);' "$gpu_preagg"
require_text 'dma_input_width_factor = Max' "$gpu_preagg"
require_text 'dma_output_width_factor = Max' "$gpu_preagg"
require_text 'estimateGpuPreAggFinalBufferSize' "$gpu_preagg"
require_text 'length < \(16UL << 20\)' "$gpu_preagg"
require_text 'TYPEALIGN\(2UL << 20, length\)' "$gpu_preagg"
require_text 'gpupreagg_setup_cost' "$gpu_preagg"
require_text 'gpupreagg_dma_cost' "$gpu_preagg"
require_text 'gpupreagg_partial_cost' "$gpu_preagg"
require_text 'con->num_groups >= 0\.5 \* input_nrows' "$gpu_preagg"
require_text 'final_buffer_per_qe' "$gpu_preagg"
require_text 'final_buffer_per_device > device_memory' "$gpu_preagg"
require_text 'path\.memory.*=' "$gpu_preagg"
require_text 'path\.rescannable.*= true' "$gpu_preagg"
require_text 'path\.sameslice_relids = con->input_rel->relids' "$gpu_preagg"
require_text 'num_parallel_trials = 1' "$gpu_preagg"
require_text 'pgstromGpuCacheIsInitialized\(\) &&' "$gpu_scan"
require_text 'pgstromGpuCacheIsInitialized\(void\)' "$gpu_cache"
require_text '!pgstrom_enable_gpucache \|\| !pgstromGpuCacheIsInitialized\(\)' "$gpu_cache"
require_text 'has_gpucache = !pgstromGpuCacheIsInitialized\(\)' "$gpu_service"
require_text 'pgstromGpuCacheIsInitialized\(\) && !has_gpucache' "$gpu_service"
require_text 'if \(pgstromGpuCacheIsInitialized\(\)\)' "$gpu_service"
require_text '__gpuContextStartWorkers\(void\)' "$gpu_service"
require_text '__gpuContextStartWorkers\(\);' "$gpu_service"
require_text 'unable to start GPU%d worker pool' "$gpu_service"
require_text 'gpuserv_shared_state->gpuserv_ready_accept = false;' "$gpu_service"
require_text 'pgstrom_gpu_service_status\(PG_FUNCTION_ARGS\)' "$gpu_service"
require_text 'service_generation' "$gpu_service"
require_text 'submitted_commands' "$gpu_service"
require_text 'cancelled_commands' "$gpu_service"
require_text 'actual_workers' "$gpu_service"
require_text "default_version = '6\.3'" "$repo_root/gpcontrib/pg_strom/src/pg_strom.control"
require_text 'pg_strom--6\.0--6\.1\.sql' "$makefile"
require_text 'pg_strom--6\.1--6\.2\.sql' "$makefile"
require_text 'pg_strom--6\.2--6\.3\.sql' "$makefile"
require_text 'gpu_service_status_local' "$upgrade_sql"
require_text 'EXECUTE ON COORDINATOR' "$upgrade_sql"
require_text 'gpu_service_status_segments' "$upgrade_sql"
require_text 'EXECUTE ON ALL SEGMENTS' "$upgrade_sql"
require_text 'CREATE VIEW pgstrom\.gpu_service_status' "$upgrade_sql"
require_text 'shared_gpu_budget_ratio' "$gpu_service"
require_text 'PTHREAD_PROCESS_SHARED' "$gpu_service"
require_text 'PTHREAD_MUTEX_ROBUST' "$gpu_service"
require_text 'gpuSharedBudgetProcessStartTime' "$gpu_service"
require_text 'gpuSharedBudgetReserve\(pool->gcontext, segment_sz\)' "$gpu_service"
require_text 'gpuSharedBudgetReserve\(GpuWorkerCurrentContext, bytesize\)' "$gpu_service"
require_text 'Reserve the full replacement while the old buffer is still live' "$gpu_service"
require_text 'Max\(kds_old->length, 16UL<<20\)' "$gpu_service"
require_text 'shared_budget_bytes' "$budget_upgrade_sql"
require_text 'local_reserved_bytes' "$budget_upgrade_sql"
require_text 'ALTER EXTENSION pg_strom UPDATE TO .6\.3.' "$budget_design"
require_text 'shared_reserved_bytes > shared_budget_bytes' "$budget_runner"
require_text 'PGSTROM_SHARED_BUDGET_CLIENTS' "$budget_runner"
require_text 'PGSTROM_SHARED_BUDGET_REQUIRE_REJECTION' "$budget_runner"
require_text 'CUDA_ERROR_OUT_OF_MEMORY' "$budget_runner"
require_text 'shared GPU budget admission rejected' "$budget_runner"
require_text 'GpuQueryBufferAllocBudgetRejected' "$gpu_service"
require_text 'shared_gpu_safety_margin_ratio' "$gpu_service"
require_text 'host_configured_budget_sum' "$gpu_service"
require_text 'budget_overcommitted' "$gpu_service"
require_text 'last_request_bytes' "$gpu_service"
require_text 'test_inject_oom' "$gpu_service"
require_text 'shared_gpu_budget_inject_oom_segments' "$budget_static_upgrade_sql"
require_text 'RETURNS SETOF integer' "$budget_static_upgrade_sql"
require_text 'SRF_RETURN_NEXT' "$gpu_service"
require_text 'host_service_count' "$budget_static_upgrade_sql"
require_text 'budget_overcommitted' "$budget_static_upgrade_sql"
require_text 'gpuscan_gpuscan' "$budget_matrix_runner"
require_text 'gpuscan_gpupreagg' "$budget_matrix_runner"
require_text 'injected query-buffer allocation failure after budget reservation' "$budget_matrix_runner"
require_text 'gp_segment_configuration' "$demo_runner"
require_text 'primary_segment_count < 2' "$demo_runner"
require_text 'segments: \$\{primary_segment_count\}' "$demo_runner"
require_text 'PGSTROM_MVP_REPEAT' "$demo_runner"
require_text 'PGSTROM_MVP_READY_TIMEOUT' "$demo_runner"
require_text 'read_service_summary' "$demo_runner"
require_text 'print_service_diagnostics' "$demo_runner"
require_text 'GPU Service readiness timed out' "$demo_runner"
require_text 'require_distribution_shape "uniform heap" pgstrom_mvp_heap' "$demo_runner"
require_text 'require_distribution_shape "skew heap" pgstrom_mvp_skew 1' "$demo_runner"
require_text 'require_distribution_shape "small heap" pgstrom_mvp_small 1' "$demo_runner"
require_text 'compare_signature "uniform heap"' "$demo_runner"
require_text 'compare_signature "skew heap"' "$demo_runner"
require_text 'compare_signature "small heap"' "$demo_runner"
require_text 'require_mixed_quals_plan "uniform heap"' "$demo_runner"
require_text 'require_mixed_quals_plan "skew heap"' "$demo_runner"
require_text 'require_mixed_quals_plan "small heap"' "$demo_runner"
require_text 'compare_signature "mixed-quals uniform heap"' "$demo_runner"
require_text 'compare_signature "mixed-quals skew heap"' "$demo_runner"
require_text 'compare_signature "mixed-quals small heap"' "$demo_runner"
require_text 'pure host-only quals unexpectedly produced a GpuScan' "$demo_runner"
require_text 'pgstrom\.gpu_service_status' "$demo_runner"
require_text 'actual_workers = configured_workers' "$demo_runner"
require_text "gpu_mempool_segment_sz = '256MB'" "$demo_config"
require_text 'gpu_mempool_max_ratio = 0\.20' "$demo_config"
require_text 'shared_gpu_budget_ratio = 0\.20' "$demo_config"
require_text 'shared_gpu_safety_margin_ratio = 0\.20' "$demo_config"
require_text "shared_gpu_budget_timeout = '5s'" "$demo_config"
require_text 'CREATE TABLE pgstrom_mvp_skew' "$demo_setup"
require_text 'CREATE TABLE pgstrom_mvp_small' "$demo_setup"
require_text 'grp_medium integer' "$demo_setup"
require_text 'grp_high integer' "$demo_setup"
require_text 'CREATE TABLE pgstrom_mvp_colocated' "$demo_setup"
require_text 'nullable_metric integer' "$demo_setup"
require_text 'DISTRIBUTED BY \(dist_key\)' "$demo_setup"
require_text 'DISTRIBUTED BY \(dist_key\)' "$demo_setup"
require_text 'EXPLAIN \(ANALYZE, VERBOSE, COSTS OFF\)' "$demo_verify"
require_text 'SET pg_strom\.cloudberry_enable_host_quals = on' "$demo_verify"
require_text 'PREPARE pgstrom_mvp_mixed_q' "$demo_verify"
require_text 'DEALLOCATE pgstrom_mvp_mixed_q' "$demo_verify"
require_text 'with-blocksize=32' "$demo_readme"
require_text 'with-wal-blocksize=32' "$demo_readme"
require_text 'PG_CONFIG="\$\(command -v pg_config\)"' "$demo_readme"
require_text 'PG_CONFIG="\$PG_CONFIG"' "$demo_readme"
require_text 'NUM_PRIMARY_MIRROR_PAIRS=2' "$demo_readme"
require_text 'WITH_MIRRORS=false' "$demo_readme"
require_text 'shared_preload_libraries=pg_strom' "$demo_readme"
require_text 'query must return .*2\|2' "$demo_readme"
require_text 'PGSTROM_MVP_ALLOW_SERVICE_RESTART' "$failure_runner"
require_text 'PGSTROM_MVP_TARGET_CONTENT' "$failure_runner"
require_text 'PGSTROM_MVP_RECOVERY_CYCLES' "$failure_runner"
require_text 'PGSTROM_MVP_SERVICE_SIGNAL' "$failure_runner"
require_text 'PGSTROM_MVP_ALLOW_HARD_FAILURE' "$failure_runner"
require_text 'kill -"\$service_signal" "\$old_service_pid"' "$failure_runner"
require_text 'UNEXPECTED_PARTIAL_RESULT' "$failure_runner"
require_text 'find_gpu_service_pid' "$failure_runner"
require_text 'worker_log_count' "$failure_runner"
require_text 'new_service_pid=.*wait_for_new_service' "$failure_runner"
require_text 'recovered_signature != "\$cpu_signature"' "$failure_runner"
require_text 'service_generation' "$failure_runner"
require_text 'service_signal == HUP' "$failure_runner"
require_text 'shared-memory epoch reset after SIGKILL' "$failure_runner"
require_text 'PGSTROM_MVP_CANCEL_CYCLES' "$cancel_runner"
require_text 'pg_cancel_backend\(\$backend_pid\)' "$cancel_runner"
require_text 'cleaning up server backend' "$cancel_runner"
require_text 'pg_terminate_backend\(pid\)' "$cancel_runner"
require_text 'application_name = .\$demo_app.' "$cancel_runner"
require_text 'pgstrom_mvp_cancel_target' "$cancel_runner"
require_text 'DO \\\$pgstrom_cancel\\\$' "$cancel_runner"
require_text 'FOR target_grp IN 1\.\.100000 LOOP' "$cancel_runner"
require_text 'cancel_scan_query=' "$cancel_runner"
require_text 'submitted > old_submitted' "$cancel_runner"
require_text 'acceptance cluster is not idle at baseline' "$cancel_runner"
require_text 'terminal_delta < submitted_delta' "$cancel_runner"
require_text 'queued == 0 && active == 0 && clients == 0' "$cancel_runner"
require_text 'PGSTROM_MVP_TEST_OPERATOR' "$cancel_runner"
require_text 'Custom Scan \(\$expected_custom_scan\)' "$cancel_runner"
require_text 'PGSTROM_MVP_TEST_OPERATOR=gpupreagg' "$gpupreagg_cancel_runner"
require_text 'PGSTROM_GPUPREAGG_CANCEL_CYCLES' "$gpupreagg_cancel_runner"
require_text 'PGSTROM_MVP_TEST_OPERATOR' "$failure_runner"
require_text 'expected_custom_scan=GpuPreAgg' "$failure_runner"
require_text 'UNEXPECTED_PARTIAL_RESULT' "$failure_runner"
require_text 'PGSTROM_MVP_TEST_OPERATOR=gpupreagg' "$gpupreagg_failure_runner"
require_text 'PGSTROM_GPUPREAGG_ALLOW_SERVICE_RESTART' "$gpupreagg_failure_runner"
require_text 'PGSTROM_GPUPREAGG_ALLOW_HARD_FAILURE' "$gpupreagg_failure_runner"
require_text 'run_failure_recovery\.sh' "$demo_readme"
require_text 'run_query_cancel\.sh' "$demo_readme"
require_text 'pg_strom\.enable_gpupreagg = off' "$demo_config"
require_text 'pg_strom\.enable_partitionwise_gpupreagg = off' "$demo_config"
require_text 'pg_strom\.enable_numeric_aggfuncs = off' "$demo_config"
require_text 'pg_strom\.enable_gpusort = off' "$demo_config"
require_text 'PGSTROM_GPUPREAGG_REPEAT' "$gpupreagg_runner"
require_text 'Custom Scan \(GpuPreAgg\)' "$gpupreagg_runner"
require_text 'GpuPreAgg Sizing.*local groups:.*per-device final buffer:' "$gpupreagg_runner"
require_text 'uniform cross-Segment groups' "$gpupreagg_runner"
require_text 'global aggregate' "$gpupreagg_runner"
require_text 'all QEs empty' "$gpupreagg_runner"
require_text 'mixed host/device quals' "$gpupreagg_runner"
require_text 'numeric aggregate' "$gpupreagg_runner"
require_text 'aggregate FILTER' "$gpupreagg_runner"
require_text 'partitioned heap' "$gpupreagg_runner"
require_text 'Gather-only GpuPreAgg MVP acceptance passed' "$gpupreagg_runner"
require_text '真实双 Primary GPU M1/M2 与 M3' "$gpupreagg_design"
require_text '最终全量回归均已通过' "$gpupreagg_design"
require_text 'query cancel 连续三轮通过' "$gpupreagg_design"
require_text 'GPU Service SIGHUP 连续三轮通过' "$gpupreagg_design"
require_text 'GPU Service SIGKILL 连续三轮通过' "$gpupreagg_design"
require_text 'M4a 结构化' "$gpupreagg_design"
require_text '成本与内存估算已于 2026-08-13 完成真实单机双 Primary' "$gpupreagg_design"
require_text 'Cloudberry Gather-only GpuPreAgg MVP acceptance passed' "$gpupreagg_design"
require_text 'PGSTROM_GPUPREAGG_M4B_REPEAT' "$gpupreagg_m4b_runner"
require_text 'gp_enable_multiphase_agg.*on' "$gpupreagg_m4b_runner"
require_text 'enable_seqscan.*on' "$gpupreagg_m4b_runner"
require_text 'low_uniform.*gpu' "$gpupreagg_m4b_runner"
require_text 'medium_uniform.*gpu' "$gpupreagg_m4b_runner"
require_text 'high_uniform.*gpu' "$gpupreagg_m4b_runner"
require_text 'near_detail_uniform.*native' "$gpupreagg_m4b_runner"
require_text 'medium_skew.*either' "$gpupreagg_m4b_runner"
require_text 'high_skew.*either' "$gpupreagg_m4b_runner"
require_text 'GpuPreAgg Cost:.*GPU setup:' "$gpupreagg_m4b_runner"
require_text 'groups actual/estimate:' "$gpupreagg_m4b_runner"
require_text 'pgstromCdbExplainTaskActual' "$repo_root/gpcontrib/pg_strom/src/executor.c"
require_text 'GpuPreAgg Actual: nitems:' "$repo_root/gpcontrib/pg_strom/src/executor.c"
require_text 'cdbexplainfun = pgstromCdbExplainTaskActual' "$repo_root/gpcontrib/pg_strom/src/executor.c"
require_text 'Motion rows: detail=' "$gpupreagg_m4b_runner"
require_text 'M4b normal-cost acceptance passed' "$gpupreagg_m4b_runner"
require_text '真实 GPU 验收全部通过' "$gpupreagg_m4b_design"
require_text 'successes=24 failures=0 waits=0 rejections=0' "$gpupreagg_m4b_design"
require_text '标记为完成' "$gpupreagg_m4b_design"
require_text 'PGSTROM_GPUPREAGG_M5A_REPEAT' "$gpupreagg_m5a_runner"
require_text 'colocated CPU local final has no pre-final Gather Motion' "$gpupreagg_m5a_runner"
require_text 'non-colocated CPU final retained Gather Motion' "$gpupreagg_m5a_runner"
require_text 'M5a colocated local-final acceptance passed' "$gpupreagg_m5a_runner"
require_text '单机 1 QD.*2 Primary' "$gpupreagg_m5a_design"
require_text '不能形成多主机、多 GPU 线性扩展' "$gpupreagg_m5a_design"
require_text 'cdbpathlocus_pull_above_projection' "$gpupreagg_m5a_design"
require_text '真实 GPU 验收全部通过' "$gpupreagg_m5a_design"
require_text '共置 GROUP BY local-final' "$gpupreagg_m5a_design"
require_text '标记为完成' "$gpupreagg_m5a_design"
if grep -Eq 'gp_enable_multiphase_agg=off|gpu_setup_cost=0|gpu_tuple_cost=0|gpu_operator_cost=0|gp_motion_cost_per_row=1000000|cpu_tuple_cost=10|cpu_operator_cost=10|enable_seqscan=off' \
    "$gpupreagg_m4b_runner" "$budget_runner" "$budget_matrix_runner"; then
    echo 'M4b acceptance runners must not contain correctness-only planner forcing' >&2
    exit 1
fi
require_text 'run_gpupreagg_mvp\.sh' "$demo_readme"
require_text 'run_gpupreagg_m4b\.sh' "$demo_readme"
require_text 'run_gpupreagg_m5a\.sh' "$demo_readme"
require_text 'run_gpupreagg_having\.sh' "$demo_readme"
require_text 'PGSTROM_GPUPREAGG_HAVING_REPEAT' "$gpupreagg_having_runner"
if grep -Eq 'enable_hashagg=off|enable_sort=off' "$gpupreagg_having_runner"; then
    echo 'HAVING runner must not use disable_cost to force aggregation paths' >&2
    exit 1
fi
require_text 'HAVING filter is not attached to the CPU final aggregate' "$gpupreagg_having_runner"
require_text 'empty aggregate HAVING NULL semantics' "$gpupreagg_having_runner"
require_text 'FILTER aggregate in HAVING' "$gpupreagg_having_runner"
require_text 'DISTINCT aggregate in HAVING' "$gpupreagg_having_runner"
require_text 'numeric aggregate in HAVING' "$gpupreagg_having_runner"
require_text 'Cloudberry GpuPreAgg HAVING acceptance passed' "$gpupreagg_having_runner"
require_text 'HAVING 不下推到 GpuPreAgg' "$gpupreagg_having_design"
require_text 'FALSE 或 UNKNOWN' "$gpupreagg_having_design"
require_text '真实 GPU 验收 runner 已实现' "$gpupreagg_having_design"
require_text 'run_gpupreagg_cancel\.sh' "$demo_readme"
require_text 'run_gpupreagg_failure_recovery\.sh' "$demo_readme"
require_text 'run_shared_gpu_budget\.sh' "$demo_readme"
require_text 'pg_strom\.cloudberry_enable_host_quals' "$host_quals_design"
require_text '没有 device qual 都不生成 GpuScan' "$host_quals_design"
require_text '真实双 Primary GPU 验收已于 2026-08-05 完成' "$host_quals_design"
require_text '76f99fafc06c1efcddb4c0b7b1f3aa870176ab54' "$host_quals_milestone"
require_text 'mixed host/device quals' "$host_quals_milestone"
require_text 'Query cancel 三轮.*通过' "$host_quals_milestone"
require_text 'SIGHUP 三轮.*通过' "$host_quals_milestone"
require_text 'SIGKILL/crash recovery 三轮.*通过' "$host_quals_milestone"
if grep -Eq 'segments: 1([^0-9]|$)' "$demo_runner"; then
    echo 'multi-segment demo must not hard-code a single QE segment' >&2
    exit 1
fi

initial_workers_line=$(grep -n '__gpuContextStartWorkers();' "$gpu_service" |
    cut -d: -f1)
ready_line=$(grep -n 'gpuserv_shared_state->gpuserv_ready_accept = true;' "$gpu_service" |
    cut -d: -f1)
if [[ -z "$initial_workers_line" || -z "$ready_line" ||
      "$initial_workers_line" -ge "$ready_line" ]]; then
    echo 'GPU Service must start workers before advertising readiness' >&2
    exit 1
fi

echo 'Cloudberry PG-Strom MVP static checks: PASS'
